#!/usr/bin/with-contenv bash

if [[ -s /cert/cert.pem ]]
then
 echo "Using existing certificate..."
else
 echo "Generating selfsigned certificate..."
 openssl req -x509 -sha256 -nodes -newkey rsa:4096 -keyout /cert/privkey.pem -days 10 -out /cert/cert.pem -batch
fi

echo "Creating nginx configuration..."

>/etc/nginx/conf.d/$VHOST.conf
echo "server {
  listen 443 ssl;
  server_name $VHOST;
  ssl_certificate /cert/cert.pem;
  ssl_certificate_key /cert/privkey.pem;

  location / {
      proxy_pass http://$TARGET/;
  }
}" >> /etc/nginx/conf.d/$VHOST.conf

nginx
tail -f /var/log/nginx/access.log
